extension Country {
    public init?(name: String) {
        switch name {
        case "United States": self = .unitedStates
        case "Afghanistan": self = .afghanistan
        case "Albania": self = .albania
        case "Algeria": self = .algeria
        case "American Samoa": self = .americanSamoa
        case "Andorra": self = .andorra
        case "Angola": self = .angola
        case "Anguilla": self = .anguilla
        case "Antarctica": self = .antarctica
        case "Antigua and Barbuda": self = .antiguaAndBarbuda
        case "Argentina": self = .argentina
        case "Armenia": self = .armenia
        case "Aruba": self = .aruba
        case "Australia": self = .australia
        case "Austria": self = .austria
        case "Azerbaijan": self = .azerbaijan
        case "Bahamas": self = .bahamas
        case "Bahrain": self = .bahrain
        case "Bangladesh": self = .bangladesh
        case "Barbados": self = .barbados
        case "Belarus": self = .belarus
        case "Belgium": self = .belgium
        case "Belize": self = .belize
        case "Benin": self = .benin
        case "Bermuda": self = .bermuda
        case "Bhutan": self = .bhutan
        case "Bolivia": self = .bolivia
        case "Bosnia and Herzegovina": self = .bosniaAndHerzegovina
        case "Botswana": self = .botswana
        case "Brazil": self = .brazil
        case "British Indian Ocean Territory": self = .britishIndianOceanTerritory
        case "Brunei Darussalam": self = .bruneiDarussalam
        case "Bulgaria": self = .bulgaria
        case "Burkina Faso": self = .burkinaFaso
        case "Burundi": self = .burundi
        case "Cambodia": self = .cambodia
        case "Cameroon": self = .cameroon
        case "Canada": self = .canada
        case "Cape Verde": self = .capeVerde
        case "Cayman Islands": self = .caymanIslands
        case "Central African Republic": self = .centralAfricanRepublic
        case "Chad": self = .chad
        case "Chile": self = .chile
        case "China": self = .china
        case "Christmas Island": self = .christmasIsland
        case "Cocos (Keeling) Islands": self = .cocosKeelingIslands
        case "Colombia": self = .colombia
        case "Comoros": self = .comoros
        case "Congo": self = .congo
        case "Democratic Republic Of The Congo": self = .democraticRepublicOfTheCongo
        case "Cook Islands": self = .cookIslands
        case "Costa Rica": self = .costaRica
        case "Cote D'ivoire": self = .coteDivoire
        case "Croatia": self = .croatia
        case "Cuba": self = .cuba
        case "Cyprus": self = .cyprus
        case "Czech Republic": self = .czechRepublic
        case "Denmark": self = .denmark
        case "Djibouti": self = .djibouti
        case "Dominica": self = .dominica
        case "Dominican Republic": self = .dominicanRepublic
        case "Ecuador": self = .ecuador
        case "Egypt": self = .egypt
        case "El Salvador": self = .elSalvador
        case "Equatorial Guinea": self = .equatorialGuinea
        case "Eritrea": self = .eritrea
        case "Estonia": self = .estonia
        case "Ethiopia": self = .ethiopia
        case "Falkland Islands (Malvinas": self = .falklandIslandsMalvinas
        case "Faroe Islands": self = .faroeIslands
        case "Fiji": self = .fiji
        case "Finland": self = .finland
        case "France": self = .france
        case "French Guiana": self = .frenchGuiana
        case "French Polynesia": self = .frenchPolynesia
        case "French Southern Territories": self = .frenchSouthernTerritories
        case "Gabon": self = .gabon
        case "Gambia": self = .gambia
        case "Germany": self = .germany
        case "Georgia": self = .georgia
        case "Ghana": self = .ghana
        case "Gibraltar": self = .gibraltar
        case "Greece": self = .greece
        case "Greenland": self = .greenland
        case "Grenada": self = .grenada
        case "Guadeloupe": self = .guadeloupe
        case "Guam": self = .guam
        case "Guatemala": self = .guatemala
        case "Guernsey": self = .guernsey
        case "Guinea": self = .guinea
        case "Guineabissau": self = .guineabissau
        case "Guyana": self = .guyana
        case "Haiti": self = .haiti
        case "Holy See (Vatican City State": self = .holySeeVaticanCityState
        case "Honduras": self = .honduras
        case "Hong Kong": self = .hongKong
        case "Hungary": self = .hungary
        case "Iceland": self = .iceland
        case "India": self = .india
        case "Indonesia": self = .indonesia
        case "Iran": self = .iran
        case "Iraq": self = .iraq
        case "Ireland": self = .ireland
        case "Isle of Man": self = .isleOfMan
        case "Israel": self = .israel
        case "Italy": self = .italy
        case "Jamaica": self = .jamaica
        case "Japan": self = .japan
        case "Jersey": self = .jersey
        case "Jordan": self = .jordan
        case "Kazakhstan": self = .kazakhstan
        case "Kenya": self = .kenya
        case "Kiribati": self = .kiribati
        case "North Korea": self = .northKorea
        case "South Korea": self = .southKorea
        case "Kuwait": self = .kuwait
        case "Kyrgyzstan": self = .kyrgyzstan
        case "Lao People's Democratic Republic": self = .laoPeoplesDemocraticRepublic
        case "Latvia": self = .latvia
        case "Lebanon": self = .lebanon
        case "Lesotho": self = .lesotho
        case "Liberia": self = .liberia
        case "Libyan Arab Jamahiriya": self = .libyanArabJamahiriya
        case "Liechtenstein": self = .liechtenstein
        case "Lithuania": self = .lithuania
        case "Luxembourg": self = .luxembourg
        case "Macao": self = .macao
        case "Macedonia": self = .macedonia
        case "Madagascar": self = .madagascar
        case "Malawi": self = .malawi
        case "Malaysia": self = .malaysia
        case "Maldives": self = .maldives
        case "Mali": self = .mali
        case "Malta": self = .malta
        case "Marshall Islands": self = .marshallIslands
        case "Martinique": self = .martinique
        case "Mauritania": self = .mauritania
        case "Mauritius": self = .mauritius
        case "Mayotte": self = .mayotte
        case "Mexico": self = .mexico
        case "Micronesia": self = .micronesia
        case "Moldova": self = .moldova
        case "Monaco": self = .monaco
        case "Mongolia": self = .mongolia
        case "Montenegro": self = .montenegro
        case "Montserrat": self = .montserrat
        case "Morocco": self = .morocco
        case "Mozambique": self = .mozambique
        case "Myanmar": self = .myanmar
        case "Namibia": self = .namibia
        case "Nauru": self = .nauru
        case "Nepal": self = .nepal
        case "Netherlands": self = .netherlands
        case "Netherlands Antilles": self = .netherlandsAntilles
        case "New Caledonia": self = .newCaledonia
        case "New Zealand": self = .newZealand
        case "Nicaragua": self = .nicaragua
        case "Niger": self = .niger
        case "Nigeria": self = .nigeria
        case "Niue": self = .niue
        case "Northern Mariana Islands": self = .northernMarianaIslands
        case "Norway": self = .norway
        case "Oman": self = .oman
        case "Pakistan": self = .pakistan
        case "Palau": self = .palau
        case "Palestinian Territory": self = .palestinianTerritory
        case "Panama": self = .panama
        case "Papua New Guinea": self = .papuaNewGuinea
        case "Paraguay": self = .paraguay
        case "Peru": self = .peru
        case "Philippines": self = .philippines
        case "Pitcairn": self = .pitcairn
        case "Poland": self = .poland
        case "Portugal": self = .portugal
        case "Puerto Rico": self = .puertoRico
        case "Qatar": self = .qatar
        case "Reunion": self = .reunion
        case "Romania": self = .romania
        case "Russian Federation": self = .russianFederation
        case "Rwanda": self = .rwanda
        case "Saint Helena": self = .saintHelena
        case "Saint Kitts and Nevis": self = .saintKittsAndNevis
        case "Saint Lucia": self = .saintLucia
        case "Saint Pierre and Miquelon": self = .saintPierreAndMiquelon
        case "Saint Vincent and The Grenadines": self = .saintVincentAndTheGrenadines
        case "Samoa": self = .samoa
        case "San Marino": self = .sanMarino
        case "Sao Tome and Principe": self = .saoTomeAndPrincipe
        case "Saudi Arabia": self = .saudiArabia
        case "Senegal": self = .senegal
        case "Serbia": self = .serbia
        case "Seychelles": self = .seychelles
        case "Sierra Leone": self = .sierraLeone
        case "Singapore": self = .singapore
        case "Slovakia": self = .slovakia
        case "Slovenia": self = .slovenia
        case "Solomon Islands": self = .solomonIslands
        case "Somalia": self = .somalia
        case "South Africa": self = .southAfrica
        case "Spain": self = .spain
        case "Sri Lanka": self = .sriLanka
        case "Sudan": self = .sudan
        case "Suriname": self = .suriname
        case "Svalbard and Jan Mayen": self = .svalbardAndJanMayen
        case "Swaziland": self = .swaziland
        case "Sweden": self = .sweden
        case "Switzerland": self = .switzerland
        case "Syrian Arab Republic": self = .syrianArabRepublic
        case "Taiwan": self = .taiwan
        case "Tajikistan": self = .tajikistan
        case "Tanzania": self = .tanzania
        case "Thailand": self = .thailand
        case "Timorleste": self = .timorleste
        case "Togo": self = .togo
        case "Tokelau": self = .tokelau
        case "Tonga": self = .tonga
        case "Trinidad and Tobago": self = .trinidadAndTobago
        case "Tunisia": self = .tunisia
        case "Turkey": self = .turkey
        case "Turkmenistan": self = .turkmenistan
        case "Turks and Caicos Islands": self = .turksAndCaicosIslands
        case "Tuvalu": self = .tuvalu
        case "Uganda": self = .uganda
        case "Ukraine": self = .ukraine
        case "United Arab Emirates": self = .unitedArabEmirates
        case "United Kingdom": self = .unitedKingdom
        case "Uruguay": self = .uruguay
        case "Uzbekistan": self = .uzbekistan
        case "Vanuatu": self = .vanuatu
        case "Venezuela": self = .venezuela
        case "Viet Nam": self = .vietNam
        case " British Virgin Islands": self = .virginIslandsUK
        case "United States Virgin Islands": self = .virginIslandsUS
        case "Wallis and Futuna": self = .wallisAndFutuna
        case "Western Sahara": self = .westernSahara
        case "Yemen": self = .yemen
        case "Zambia": self = .zambia
        case "Zimbabwe": self = .zimbabwe
        case "All Countries": self = .allCountries
        default: return nil
        }
    }
}
