name: Send release email
on:
  push:
    branches:
    - release
jobs:
  send_email:
    runs-on: ubuntu-latest
    name: send_email
    steps:
    - name: Send email
      # You may pin to the exact commit or the version.
      # uses: dawidd6/action-send-mail@98b61f505d216dafd844f3bfca5b2972df822dab
      uses: dawidd6/action-send-mail@v3.1.0
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Required mail server username:
        username: ${{secrets.MAIL_AGENT_USERNAME}}
        # Required mail server password:
        password: ${{secrets.MAIL_AGENT_PASSWORD}}
        # Required mail subject:
        subject: Litewallet iOS Release almost ready
        # Required recipients' addresses:
        to: ${{secrets.MAIL_ORI}},${{secrets.MAIL_KERRY}}
        # Required sender full name (address can be skipped):
        from:  <litecoin.foundation.mobile.agent@gmail.com> # <user@example.com> Litewallet iOS Github Repo 
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        html_body: file://README.html
        # Optional carbon copy recipients:
        cc: kerry.washington.uk@gmail.com 
        # Optional recipient of the email response:
        reply_to: litecoin.foundation.mobile.agent@gmail.com
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
